version: "3.5"

services:
  lumen:
    ports:
      - "8000:8000"
    volumes:
      - app_storage:/var/www/storage
      - .:/var/www/
      - /var/www/vendor/
    build: .
    command: php -S lumen:8000 -t public
    restart: always
    depends_on:
      - db
    links:
     - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: dev_transaction
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_user
      MYSQL_ROOT_PASSWORD: eduardo
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql:rw
volumes:
  app_storage:
  db-data:
